
services:
  web:
    build: .
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/lithflow
      - SECRET_KEY=dev-secret-key-change-in-production
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./:/app
    command: gunicorn --bind 0.0.0.0:5000 "run:app"

  db:
    image: timescale/timescaledb:latest-pg14
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=lithflow
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  data_pipeline:
    build: .
    restart: always
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/lithflow
      - SECRET_KEY=dev-secret-key-change-in-production
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./:/app
    command: python -m data_pipeline.schedulers.scheduler

volumes:
  postgres_data:
  redis_data: